name: Build / Test / Push

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-image: ${{ steps.build-meta.outputs.tags }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Produce the build image tag
        id: build-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=sha,suffix=-build-${{ github.run_id }}_${{ github.run_attempt }}

      - name: Build and push the untested image
        uses: docker/build-push-action@v6
        with:
          push: true
          labels: ${{ steps.build-meta.outputs.labels }}
          tags: ${{ steps.build-meta.outputs.tags }}
          provenance: true
          cache-from: type=gha
          cache-to: type=gha

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    env:
      DOCKER_APP_IMAGE: ${{ needs.build.outputs.build-image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run the tests
        run: bin/test
        env:
          COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml

  push:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Produce permanent image tags
        id: branch-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Retag and push the image
        uses: docker/build-push-action@v6
        with:
          push: true
          labels: ${{ steps.branch-meta.outputs.labels }}
          tags: ${{ steps.branch-meta.outputs.tags }}
          cache-from: type=registry,ref=${{ needs.build.outputs.build-image }}
