name: Build / Test / Push

on:
  workflow_call:
  workflow_dispatch:

env:
  COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
  DOCKER_METADATA_SET_OUTPUT_ENV: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Produce image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Fetch the sha-based image tag
        run: echo "$DOCKER_METADATA_OUTPUT_TAGS" | grep -m1 ':sha-' | xargs | sed 's/^/DOCKER_APP_IMAGE=/' >> $GITHUB_ENV

      - name: Build the image
        id: build
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          provenance: true
          cache-from: type=registry,ref=${{ env.DOCKER_APP_IMAGE }}

      - name: Run the tests
        run: bin/test
