name: Test Image

on:
  workflow_call:
    inputs:
      image:
        description: Full ID of the image to be tested
        required: true
        type: string
  workflow_dispatch:
    inputs:
      image:
        description: Full ID of the image to be tested
        required: true
        type: string

env:
  COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
  DOCKER_APP_IMAGE: ${{ inputs.image }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Start the stack
        run: docker compose up --detach --no-build --pull=always

      - name: Run the test command
        run: bin/test
